package app.ascend.games.engine.games.lightsout

import app.ascend.games.engine.core.Daily

/**
 * Lights Out (5x5). Pressing a cell toggles it and its orthogonal neighbours;
 * clear every light to win.
 *
 * Daily boards are generated by applying random presses to a solved (all-off)
 * board — any position reachable that way is guaranteed solvable, and the press
 * operation is its own inverse so no separate solver is needed.
 */
object LightsOutEngine {
    const val SIZE = 5

    fun daily(epochDay: Long, scrambles: Int = 7): BooleanArray {
        val rng = Daily.random(epochDay, "lightsout")
        val lights = BooleanArray(SIZE * SIZE)
        repeat(scrambles) { press(lights, rng.nextInt(SIZE * SIZE)) }
        if (lights.none { it }) press(lights, 0) // never hand out an already-solved board
        return lights
    }

    fun press(lights: BooleanArray, cell: Int) {
        val r = cell / SIZE; val c = cell % SIZE
        toggle(lights, r, c)
        toggle(lights, r - 1, c)
        toggle(lights, r + 1, c)
        toggle(lights, r, c - 1)
        toggle(lights, r, c + 1)
    }

    private fun toggle(lights: BooleanArray, r: Int, c: Int) {
        if (r in 0 until SIZE && c in 0 until SIZE) lights[r * SIZE + c] = !lights[r * SIZE + c]
    }

    fun isSolved(lights: BooleanArray): Boolean = lights.none { it }
}
